[build-system]
requires = [ "setuptools", "setuptools_scm" ]
build-backend = "setuptools.build_meta"

[project]
name = "uranography"
description = "Tools for visualization of the celestial sphere."
readme = "README.md"
authors = [
    {name="Eric H. Neilsen, Jr.", email="neilsen@fnal.gov"},
]
classifiers = [ 
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Astronomy",
 ]
dynamic = [ "version" ]
dependencies = [
    "numpy",
    "pandas",
    "astropy >= 5.3",
    "healpy",
    "healsparse",
    "bokeh >= 3.1.1",
    "panel >= 1.1.0",
    "colorcet",
    "jupyter",
    "nbconvert",
    "selenium",
]

[project.urls]
"Homepage" = "https://github.com/lsst/uranography"

[project.optional-dependencies]
test = [
    "pytest",
    "black == 22.10.0",
    "pytest-black == 0.3.12",
    "flake8 == 4.0.1",
    "pytest-flake8 == 1.1.1",
]

[tool.setuptools.dynamic]
version = { attr = "setuptools_scm.get_version" }

[tool.setuptools.packages.find]
where = [ "" ]

[tool.setuptools_scm]
write_to = "uranography/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""

[tool.pytest.ini_options]
addopts = "--flake8 --black --ignore-glob=*/version.py"
flake8-ignore = ["E133", "E203", "E226", "E228", "N802", "N803", "N806", "N812", "N813", "N815", "N816", "W503", "**/*/__init__.py ALL", "**/*/version.py ALL"]
flake8-max-line-length = 110
flake8-max-doc-length = 79
testpaths = "."
